### ISSUE TITLE
Exercises never initialized

### ISSUE THREAD

**Issue by cameronmarlow** [guanzgrace/stretch#7]
`exercisesLastSaved` is never initalized so the initial fetch never happens.

```javascript
var isExerciseTooOld = false;
chrome.storage.local.get('exercisesLastSaved', function(date) {
...
}
```

**Comment by guanzgrace** [comment]
Even if it's never been initialized, Chrome should query for it and return null. I've put in this line to account for that.
`if (date == null) { queryAPI(); }`
