### ISSUE TITLE
Clicking frequency opens page

### ISSUE THREAD

**Issue by cameronmarlow** [guanzgrace/stretch#8]
When clicking the frequency toggle, it opens a new stretch page. The desired behavior would be to simply switch the setting as it does with enable/disable

**Comment by guanzgrace** [comment]
Instead of recreating the alarm here, I've changed this call to no longer include a call to `recreateAlarm()`
```
chrome.storage.onChanged.addListener(function(changes, namespace) {
    var changedItems = Object.keys(changes);
    for (var item of changedItems) {
        console.log(item + " has changed in storage: " + 
            " Old value: " + changes[item].oldValue +
            " New value: " + changes[item].newValue);
    }
});
```
